{% set name = "ofiber" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ofiber-{{ version }}.tar.gz
  sha256: 4ec1421f1ba01877552ecaace4c0f01b1726e6eee6dd9ce8bbd1cd7a0b5bad14

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=44
  run:
    - pip
    - python >={{ python_min }}
    - matplotlib-base
    - numpy
    - scipy

test:
  imports:
    - ofiber
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/scottprahl/ofiber
  summary: A python module for mode and power calculations for optical fibers.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE.txt
  doc_url: https://ofiber.readthedocs.io/
  dev_url: https://github.com/scottprahl/ofiber

extra:
  recipe-maintainers:
    - scottprahl
